name: dartzen
repository: https://github.com/DartZenDev/DartZen

packages:
  - packages/**
  - apps/**/**


command:
  version:
    # Use independent versioning for each package
    # Versions are calculated automatically based on conventional commits
    message: "chore(release): publish packages"
    linkToCommits: true
    workspaceChangelog: true
    # Use conventional commits to determine version bumps
    # feat: minor version bump (0.1.0 -> 0.2.0)
    # fix: patch version bump (0.1.0 -> 0.1.1)
    # BREAKING CHANGE: major version bump (0.1.0 -> 1.0.0)
    branch: main

  bootstrap:
    # It seems so that running "pub get" in parallel can have issues (like
    # https://github.com/dart-lang/pub/issues/3404)
    runPubGetInParallel: false
