include: ../dartzen_core/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/generated/**"

linter:
  rules:
    prefer_relative_imports: true
    avoid_relative_lib_imports: false
    always_use_package_imports: false

custom_lint:
  rules:
    sort_pub_dependencies: true
    sort_directives: true
    prefer_final_locals: true
    prefer_const_constructors: true
    avoid_print: true

dart:
  line-length: 100
  indent: 2
  trailing-comma: true
  sort-constructor-parameters: true

fix:
  format: true
  sort-imports: true
